### Задание 1. Загрузка данных
Изучить представленный набор данных на основе описания его столбцов, загрузить его и оставить 8 столбцов для дальнейшего изучения: surgery?, Age, rectal temperature, pulse, respiratory rate, temperature of extremities, pain, outcome.

In [273]:
import pandas as pd

In [274]:
import numpy as np

In [275]:
df = pd.read_csv('horse_data.csv', na_values = '?')
df.head()

,2,1,530101,38.50,66,28,3,3.1,?,2.1,...,45.00,8.40,?.4,?.5,2.2,2.3,11300,00000,00000.1,2.4
0,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
1,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
2,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
3,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
4,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2

In [276]:
### переименуем необходимые для анализа столбцы
df.rename(columns = {'2':'surgery?', '1':'Age', '38.50':'rectal temperature', '66':'pulse', '28': 'respiratory rate', '3':'temperature of extremities', '5':'pain', '2.2':'outcome'}, inplace=True)

In [277]:
df_new = df[['surgery?','Age','rectal temperature','pulse','respiratory rate','temperature of extremities','pain', 'outcome']]
df_new.head(20)

,surgery?,Age,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
0,1.0,1,39.2,88.0,20.0,NaN,3.0,3.0
1,2.0,1,38.3,40.0,24.0,1.0,3.0,1.0
2,1.0,9,39.1,164.0,84.0,4.0,2.0,2.0
3,2.0,1,37.3,104.0,35.0,NaN,NaN,2.0
4,2.0,1,NaN,NaN,NaN,2.0,2.0,1.0
5,1.0,1,37.9,48.0,16.0,1.0,3.0,1.0
6,1.0,1,NaN,60.0,NaN,3.0,NaN,2.0
7,2.0,1,NaN,80.0,36.0,3.0,4.0,3.0
8,2.0,9,38.3,90.0,NaN,1.0,5.0,1.0
9,1.0,1,38.1,66.0,12.0,3.0,3.0,1.0
10,2.0,1,39.1,72.0,52.0,2.0,2.0,1.0
11,1.0,1,37.2,42.0,12.0,2.0,3.0,1.0
12,2.0,9,38.0,92.0,28.0,1.0,1.0,2.0
13,1.0,1,38.2,76.0,28.0,3.0,3.0,1.0
14,1.0,1,37.6,96.0,48.0,3.0,5.0,2.0
15,1.0,9,NaN,128.0,36.0,3.0,4.0,2.0
16,2.0,1,37.5,48.0,24.0,NaN,NaN,1.0
17,1.0,1,37.6,64.0,21.0,1.0,2.0,1.0
18,2.0,1,39.4,110.0,35.0,4.0,NaN,1.0
19,1.0,1,39.9,72.0,60.0,1.0,5.0,1.0

### Задание 2. Первичное изучение данных
Проанализировать значения по столбцам, рассчитать базовые статистики, найти выбросы.

In [278]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   surgery?                    298 non-null    float64
 1   Age                         299 non-null    int64
 2   rectal temperature          239 non-null    float64
 3   pulse                       275 non-null    float64
 4   respiratory rate            241 non-null    float64
 5   temperature of extremities  243 non-null    float64
 6   pain                        244 non-null    float64
 7   outcome                     298 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 18.8 KB

In [279]:
### рассчитаем бзовые статистики
df_new.describe()

,surgery?,Age,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
count,298.000000,299.00000,239.000000,275.000000,241.000000,243.000000,244.000000,298.000000
mean,1.395973,1.64214,38.166527,71.934545,30.427386,2.345679,2.942623,1.550336
std,0.489881,2.17730,0.733508,28.680522,17.678256,1.046369,1.303993,0.737967
min,1.000000,1.00000,35.400000,30.000000,8.000000,1.000000,1.000000,1.000000
25%,1.000000,1.00000,37.800000,48.000000,18.000000,1.000000,2.000000,1.000000
50%,1.000000,1.00000,38.200000,64.000000,24.000000,3.000000,3.000000,1.000000
75%,2.000000,1.00000,38.500000,88.000000,36.000000,3.000000,4.000000,2.000000
max,2.000000,9.00000,40.800000,184.000000,96.000000,4.000000,5.000000,3.000000

In [280]:
df_new.groupby('surgery?').mean()

,Age,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
surgery?,,,,,,,
1.0,1.80000,38.143571,76.396341,33.375000,2.450000,3.293706,1.622222
2.0,1.40678,38.201020,65.500000,26.114583,2.196078,2.430000,1.440678

In [281]:
df_new.groupby('Age').mean()

,surgery?,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
Age,,,,,,,
1,1.408759,38.122831,67.462451,28.239819,2.361233,2.929515,1.551095
9,1.250000,38.645000,123.363636,54.600000,2.125000,3.117647,1.541667

In [282]:
df_new.groupby('surgery?').median()

,Age,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
surgery?,,,,,,,
1.0,1,38.1,70.0,28.0,3.0,3.0,1.0
2.0,1,38.2,55.0,24.0,2.0,2.0,1.0

In [283]:
df_new.groupby('Age').median()

,surgery?,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
Age,,,,,,,
1,1.0,38.1,60.0,24.0,3.0,3.0,1.0
9,1.0,38.6,124.0,49.0,2.5,3.0,1.5

In [284]:
### рассчитаем Моду:
print('Значение Моды показателя sergery?:',df_new['surgery?'].mode()[0])
print('Значение Моды показателя Age:',df_new['Age'].mode()[0])
print('Значение Моды показателя rectal temperature:',df_new['rectal temperature'].mode()[0])
print('Значение Моды показателя pulse:', df_new['pulse'].mode()[0])
print('Значение Моды показателя respiratory rate:',df_new['respiratory rate'].mode()[0])
print('Значение Моды показателя temperature of extremities:',df_new['temperature of extremities'].mode()[0])
print('Значение Моды показателя pain:',df_new['pain'].mode()[0])
print('Значение Моды показателя outcome:',df_new['outcome'].mode()[0])

Значение Моды показателя sergery?: 1.0
Значение Моды показателя Age: 1
Значение Моды показателя rectal temperature: 38.0
Значение Моды показателя pulse: 48.0
Значение Моды показателя respiratory rate: 20.0
Значение Моды показателя temperature of extremities: 3.0
Значение Моды показателя pain: 3.0
Значение Моды показателя outcome: 1.0

### Выбросы

In [285]:
### рассчитаем Выбросы для показателя sergery?:
q1 = df_new['surgery?'].quantile(0.25)
q3 = df_new['surgery?'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)

-0.5 3.5

In [286]:
#Так как показатеь sergery принимает только 2 значения: 1 или 2, при расчете средних статистик min = 1, max = 2, то будем считать,
# что выбросов нет.

In [287]:
### рассчитаем Выбросы для показателя Age:
q1 = df_new['Age'].quantile(0.25)
q3 = df_new['Age'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)

1.0 1.0

In [288]:
# Верхняя и нижняя границы выбросов = 1, но max значение показателя age = 9, скорее всего данные введены ошибочно, так как
# показатель может принимать только значения 1 и 2. Будем считать все значения > 2 выбросами.

In [289]:
print(df['Age'].mean())
print(df[(df['Age'] < 2)]['Age'].mean())
print(df['Age'].median())
print(df[(df['Age'] < 2)]['Age'].median())
print(df['Age'].mode()[0])
print(df[(df['Age'] < 2)]['Age'].mode()[0])

1.6421404682274248
1.0
1.0
1.0
1
1

In [290]:
### рассчитAgeаем Выбросы для показателя rectal temperature:
q1 = df_new['rectal temperature'].quantile(0.25)
q3 = df_new['rectal temperature'].quantile(0.75)
iqr = q3 - q1
lower_bound = (q1 - (1.5 * iqr)).round() 
upper_bound = q3 + (1.5 * iqr).round() 
print(lower_bound, upper_bound)

37.0 39.5

In [291]:
print(df['rectal temperature'].mean())
print(df[(df['rectal temperature'] > 34) & (df['rectal temperature'] < 40)]['rectal temperature'].mean())
print(df['rectal temperature'].median())
print(df[(df['rectal temperature'] > 34) & (df['rectal temperature'] < 40)]['rectal temperature'].median())
print(df['rectal temperature'].mode()[0])
print(df[(df['rectal temperature'] > 34) & (df['rectal temperature'] < 40)]['rectal temperature'].mode()[0])

38.166527196652744
38.12936170212768
38.2
38.1
38.0
38.0

In [292]:
# Можно сделать вывод о том, что выбросы фактически не окаывают влияние на значение средних метрик.

In [293]:
### рассчитаем Выбросы для показателя pulse:
q1 = df_new['pulse'].quantile(0.25)
q3 = df_new['pulse'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)
remove_outliers = df_new[df_new['pulse'].between(lower_bound, upper_bound, inclusive=True)]
remove_outliers
pd.concat([df_new, remove_outliers]).drop_duplicates(keep=False)

-12.0 148.0

,surgery?,Age,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
2,1.0,9,39.1,164.0,84.0,4.0,2.0,2.0
4,2.0,1,NaN,NaN,NaN,2.0,2.0,1.0
40,2.0,9,39.0,150.0,72.0,NaN,NaN,1.0
51,2.0,1,NaN,NaN,NaN,1.0,1.0,1.0
54,1.0,9,38.6,160.0,20.0,3.0,3.0,2.0
57,1.0,1,NaN,NaN,20.0,4.0,5.0,2.0
73,1.0,9,NaN,NaN,NaN,NaN,NaN,2.0
92,2.0,1,NaN,NaN,NaN,3.0,5.0,2.0
114,2.0,1,NaN,NaN,40.0,3.0,3.0,1.0
116,2.0,1,39.5,NaN,NaN,3.0,3.0,3.0
125,1.0,1,38.7,NaN,NaN,3.0,5.0,1.0
150,1.0,1,39.3,NaN,NaN,4.0,4.0,2.0
158,2.0,1,NaN,NaN,12.0,1.0,2.0,1.0
159,1.0,1,NaN,NaN,NaN,NaN,4.0,1.0
173,2.0,1,NaN,NaN,NaN,3.0,4.0,2.0
203,1.0,1,39.2,NaN,23.0,3.0,4.0,1.0
215,2.0,1,NaN,NaN,NaN,NaN,NaN,1.0
226,1.0,9,NaN,NaN,NaN,NaN,NaN,1.0
254,1.0,9,38.8,184.0,84.0,1.0,4.0,2.0
274,1.0,9,38.8,150.0,50.0,1.0,5.0,2.0

In [294]:
print(df['pulse'].mean())
print(df[(df['pulse'] > -12) & (df['pulse'] < 148)]['pulse'].mean())
print(df['pulse'].median())
print(df[(df['pulse'] > -12) & (df['pulse'] < 148)]['pulse'].median())
print(df['pulse'].mode()[0])
print(df[(df['pulse'] > -12) & (df['pulse'] < 148)]['pulse'].mode()[0])

71.93454545454546
70.27407407407408
64.0
64.0
48.0
48.0

In [295]:
# Можно сделать вывод о том, что выбросы фактически не окаывают влияние на значение средних метрик показателя pulse.

In [296]:
### рассчитаем Выбросы для показателя respiratory rate:
q1 = df_new['respiratory rate'].quantile(0.25)
q3 = df_new['respiratory rate'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)

-9.0 63.0

In [297]:
print(df['respiratory rate'].mean())
print(df[(df['respiratory rate'] > -9) & (df['respiratory rate'] < 63)]['respiratory rate'].mean())
print(df[(df['respiratory rate'] > -9) & (df['respiratory rate'] < 96)]['respiratory rate'].mean())
print(df['respiratory rate'].median())
print(df[(df['respiratory rate'] > -9) & (df['respiratory rate'] < 63)]['respiratory rate'].median())
print(df['respiratory rate'].mode()[0])
print(df[(df['respiratory rate'] > -9) & (df['respiratory rate'] < 63)]['respiratory rate'].mode()[0])

30.42738589211618
26.709821428571427
29.87866108786611
24.0
24.0
20.0
20.0

In [298]:
# Верхняя граница выбросов 63, но max значение показателя respiratory rate 96, то есть существуют значения показателя значительно
# превышающие верхнюю границу выбросов. Значительное искажение при расчете ср. арифметического, остальные базовые метрики без изменений.

In [299]:
### рассчитаем Выбросы для показателя temperature of extremities:
q1 = df_new['temperature of extremities'].quantile(0.25)
q3 = df_new['temperature of extremities'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)

-2.0 6.0

In [300]:
print(df['temperature of extremities'].mean())
print(df[(df['temperature of extremities'] > -2) & (df['temperature of extremities'] < 6)]['temperature of extremities'].mean())
print(df['temperature of extremities'].median())
print(df[(df['temperature of extremities'] > -2) & (df['temperature of extremities'] < 6)]['temperature of extremities'].median())
print(df['temperature of extremities'].mode()[0])
print(df[(df['temperature of extremities'] > -2) & (df['temperature of extremities'] < 6)]['temperature of extremities'].mode()[0])

2.345679012345679
2.345679012345679
3.0
3.0
3.0
3.0

In [301]:
# Выбросы не вляют на расчет базовых метрик. Согласно описнию выбросами можно считать все данные меньше 1  больше 4.

In [304]:
### рассчитаем Выбросы для показателя pain:
q1 = df_new['pain'].quantile(0.25)
q3 = df_new['pain'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)

-1.0 7.0

In [305]:
print(df['pain'].mean())
print(df[(df['pain'] > -1) & (df['pain'] < 7)]['pain'].mean())
print(df['pain'].median())
print(df[(df['pain'] > -1) & (df['pain'] < 7)]['pain'].median())
print(df['pain'].mode()[0])
print(df[(df['pain'] > -1) & (df['pain'] < 7)]['pain'].mode()[0])

2.942622950819672
2.942622950819672
3.0
3.0
3.0
3.0

In [306]:
# Выбросы не вляют на расчет базовых метрик. Согласно описнию выбросами можно считать все данные меньше 1  больше 5.

In [307]:
### рассчитаем Выбросы для показателя outcome:
q1 = df_new['outcome'].quantile(0.25)
q3 = df_new['outcome'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
print(lower_bound, upper_bound)

-0.5 3.5

In [308]:
print(df['outcome'].mean())
print(df[(df['outcome'] > -0.5) & (df['outcome'] < 3.5)]['outcome'].mean())
print(df['outcome'].median())
print(df[(df['outcome'] > -0.5) & (df['outcome'] < 3.5)]['outcome'].median())
print(df['outcome'].mode()[0])
print(df[(df['outcome'] > -0.5) & (df['outcome'] < 3.5)]['outcome'].mode()[0])

1.5503355704697988
1.5503355704697988
1.0
1.0
1.0
1.0

In [309]:
# Выбросы не вляют на расчет базовых метрик. Согласно описнию выбросами можно считать все данные меньше 1  больше 3.

#### Заполнение пропусков по каждому показателю отдельно на основании полученных статистических расчетов

In [310]:
### Расчет количества пропусков в %:
(df_new.isna().mean() * 100).round(2)

surgery?                       0.33
Age                            0.00
rectal temperature            20.07
pulse                          8.03
respiratory rate              19.40
temperature of extremities    18.73
pain                          18.39
outcome                        0.33
dtype: float64

In [311]:
# 1. По показателю surgery? мы имеем 1 пропуск, это категория, которая отражает была ли сделана операция лошади или нет.
# Выбросы не будем брать в расчет, так как скорее всего они были внесены ошибочно.
# Так как есть только 2 варианта ответа, пропуск заполняем наиболее часто встречающимся (Модой).

# 2. По показателю rectal temperature 20% пропусков (60). Проанализировав средние показатели (ср. арифметическое, моду, медиану),
# max и min значение, а также сделав вывод о том, что температура не зависит от того, был ли сделана лошади операция или нет
# можно принять решение о замене пропусков средним арифметическим значением. Были рассчитана средняя температура для лошадей разного
# возраста и лашадей, у которх была проведена операция, и без операции, температура мало отличается.

# 3.По показателю pulse 8% пропусков (24). Есть существенные выбросы в данных.
# Нормальный пульс у лошади в состоянии покоя составляет от 25 до 40 ударов в минуту. 
#Если пульс измеряли после тренировки лошади или в ожидании предстоящей тренировки у большинства лошадей пульс поднимается до 48-60 уд/мин.
#Если лошадь напугана или находится в состоянии шока симпатическая нервная система выделяет эпинефрин (адреналин),
#который пересиливает тонус блуждающего нерва и может быстро поднять частоту пульса лошади до 220-240 уд/мин. Возможно выбросы связаны именно с этим обстоятельством. 
# Согласно приведенным в таблице данным на пульс не влияет факт проведения операции, но существенно влияет возраст. 
# Так как pulse относится к непрерывным данным, заменим все пропуски этого показателя Медианой в разрезе возраста.

# 4. По показателю respiratory rate 19% пропусков (58).Все рассчитанные средние значения значительно превышают нормальную частоту дыхания,
#которая должны быть от 8-10. Это скорее вего связано с болезнью животных.
#Частота дыхания возрастает при стрессе, повышении температуры и респираторных заболеваниях.
#Существенная разница базовых метрик в разрезе возраста лошадей.
# Так как есть выбросы в данных, и при расчете ср. арифметичекого выбросы оказываю влияние и искажают этот показатель
# заменим существующие пропуски медианой сгруппировав данные по возрасту.

# 5. По показателю temperature of extremities 18.7% пропусков (56). Есть выбросы. Значения Моды и Медианы равны.
# Заменим пропуски Модой, так как это категориальый показатель.

# 6. По показателю pain 18.4% пропусков (55).Есть выбросы. Значения Моды и Медианы равны. 
# Заменим пропуски Модой, так как это категориальый показатель.

# 7.По показателю outcome мы имеем 1 пропуск, это категория. Есть выбросы. Значения Моды и Медианы равны. 
# Заменим пропуски Модой,так как это категориальый показатель.

In [315]:
df_new['surgery?'].fillna(df_new['surgery?'].mode()[0], inplace=True)
df_new['rectal temperature'].fillna(df_new['rectal temperature'].mean, inplace=True)
df_new['pulse'].fillna(df_new.groupby('Age')['pulse'].transform('median'), inplace=True)
df_new['respiratory rate'].fillna(df_new.groupby('Age')['respiratory rate'].transform('median'), inplace=True)
df_new['temperature of extremities'].fillna(df_new['temperature of extremities'].mode()[0], inplace=True)
df_new['pain'].fillna(df_new['pain'].mode()[0], inplace=True)
df_new['outcome'].fillna(df_new['outcome'].mode()[0], inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

In [316]:
df_new.describe()

,surgery?,Age,pulse,respiratory rate,temperature of extremities,pain,outcome
count,299.000000,299.00000,299.000000,299.000000,299.000000,299.000000,299.000000
mean,1.394649,1.64214,71.404682,29.515050,2.468227,2.953177,1.548495
std,0.489595,2.17730,28.013422,16.216518,0.976997,1.177736,0.737415
min,1.000000,1.00000,30.000000,8.000000,1.000000,1.000000,1.000000
25%,1.000000,1.00000,48.000000,20.000000,1.000000,2.000000,1.000000
50%,1.000000,1.00000,60.000000,24.000000,3.000000,3.000000,1.000000
75%,2.000000,1.00000,88.000000,36.000000,3.000000,4.000000,2.000000
max,2.000000,9.00000,184.000000,96.000000,4.000000,5.000000,3.000000

In [317]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   surgery?                    299 non-null    float64
 1   Age                         299 non-null    int64
 2   rectal temperature          299 non-null    object
 3   pulse                       299 non-null    float64
 4   respiratory rate            299 non-null    float64
 5   temperature of extremities  299 non-null    float64
 6   pain                        299 non-null    float64
 7   outcome                     299 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 18.8+ KB

In [272]:
df_new.head(10)

RecursionError: maximum recursion depth exceeded in comparison

RecursionError: maximum recursion depth exceeded in comparison